// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU3rmKxAG5c8aumbyi30so3V4ZGSJ3OVM',
    appId: '1:921290435175:web:a51910b1de9f1e182bc2c2',
    messagingSenderId: '921290435175',
    projectId: 'triveous-news-app',
    authDomain: 'triveous-news-app.firebaseapp.com',
    storageBucket: 'triveous-news-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyp0NBHVsNjv8Ig5m-TpdXWhMZ7rOsnto',
    appId: '1:921290435175:android:223d5a33ca41165d2bc2c2',
    messagingSenderId: '921290435175',
    projectId: 'triveous-news-app',
    storageBucket: 'triveous-news-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVp6i6CKFY2OQHSgYuSNo-aQ3qOzpwJQ',
    appId: '1:921290435175:ios:a584d9f4cf06ec972bc2c2',
    messagingSenderId: '921290435175',
    projectId: 'triveous-news-app',
    storageBucket: 'triveous-news-app.appspot.com',
    iosClientId: '921290435175-9094h2dn5bss0j3o5idlto953aiic800.apps.googleusercontent.com',
    iosBundleId: 'com.example.saathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcVp6i6CKFY2OQHSgYuSNo-aQ3qOzpwJQ',
    appId: '1:921290435175:ios:ed8b949433b9a3032bc2c2',
    messagingSenderId: '921290435175',
    projectId: 'triveous-news-app',
    storageBucket: 'triveous-news-app.appspot.com',
    iosClientId: '921290435175-i6go0tnj1gtnmg95s7u7u18ejni3uh7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.saathi.RunnerTests',
  );
}
